# Generated by Django 3.1.1 on 2022-01-23 22:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='boat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='boat_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('correction', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participant_management.boat')),
            ],
        ),
        migrations.CreateModel(
            name='race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('end_date', models.DateField()),
                ('start_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='rower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('gender', models.CharField(choices=[('f', 'Female'), ('m', 'Male')], default='f', max_length=1)),
                ('date_of_birth', models.DateField(default=datetime.datetime(2000, 1, 1, 0, 0))),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='heat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('distance', models.IntegerField(verbose_name='Distance (m)')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('crews', models.ManyToManyField(to='participant_management.crew')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participant_management.race')),
            ],
        ),
        migrations.AddField(
            model_name='crew',
            name='rowers',
            field=models.ManyToManyField(to='participant_management.rower'),
        ),
        migrations.AddField(
            model_name='boat',
            name='boat_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participant_management.boat_type'),
        ),
    ]
