# Generated by Django 3.1.1 on 2022-01-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rower',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
