# Generated by Django 3.1.1 on 2022-01-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant_management', '0002_auto_20220123_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='slug',
            field=models.SlugField(default='testslug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='heat',
            name='slug',
            field=models.SlugField(default='testslug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='race',
            name='slug',
            field=models.SlugField(default='testslug'),
            preserve_default=False,
        ),
    ]
