# Generated by Django 3.1.1 on 2022-01-23 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participant_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField()),
                ('finish_time', models.DateTimeField()),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participant_management.crew')),
                ('heat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participant_management.heat')),
            ],
        ),
    ]
